# Example ESPHome configuration using the external Modbus TCP component

esphome:
  name: modbus-tcp-test
  platform: ESP32
  board: esp32dev

# Add external component
external_components:
  - source: github://Gucioo/esphome_modbus_tcp_master/
    components: [modbus_tcp_16]
    refresh: 0s
  # OR for local development:
  # - source:
  #     type: local
  #     path: /path/to/your/components
  #   components: [modbus_tcp]

wifi:
  ssid: "your_wifi_ssid"
  password: "your_wifi_password"

# Enable logging
logger:
  level: INFO
# Enable Home Assistant API
api:
  encryption:
    key: "your_api_key"

ota:
  password: "your_ota_password"

# Configure the Modbus TCP sensor
sensor:
  - platform: modbus_tcp_16
    name: "AI1 LOGO Temperature Sensor"
    host: "192.168.0.3"
    port: 502                    # Optional, defaults to 502
    functioncode: 4              # Optional, defaults to 3 (Read Holding Registers)0x40 000, 4 Read Input Register 0x30 000
    register_address: 0          # Your register address - Starts from 0
    scale: 0.1                   # Optional, defaults to 0.1 (multiply raw value by 0.1)
    update_interval: 10s         # Optional, defaults to 30s
    unit_of_measurement: "°C"
    device_class: "temperature"
    accuracy_decimals: 1
  - platform: modbus_tcp_16
    name: "AI2 LOGO Temperature Sensor"
    host: "192.168.0.3"
    port: 502                    # Optional, defaults to 502
    functioncode: 4              # Optional, defaults to 3 (Read Holding Registers)0x40 000, 4 Read Input Register 0x30 000
    register_address: 1          # Your register address - Starts from 0
    scale: 0.1                   # Optional, defaults to 0.1 (multiply raw value by 0.1)
    update_interval: 10s         # Optional, defaults to 30s
    unit_of_measurement: "°C"
    device_class: "temperature"
    accuracy_decimals: 1
